### ISSUE TITLE
Change logo to svg

### ISSUE THREAD

**Issue by carlashworth** [big-band-roulette/musicians-portal#32]
Self explanatory - but would prevent it being blurred on phones.

**Comment by THargreaves** [comment]
I actually changed it to a PNG from an SVG because the SVG was blurring at the small logo resolution. See
https://graphicdesign.stackexchange.com/questions/48991/svg-looking-bad-in-small-resolution

You're right though, the PNG does look blurry too. Perhaps rendering the SVG as a PNG at the correct resolution and using that for the logo is the best way?

**Comment by carlashworth** [comment]
I think I might have found a solution using a thing called pixelsnap in inkscape https://code.google.com/archive/p/pixelsnap/ - but I can't replicate the issue... I'll make a PR here and if you think I've solved it we can use this solution?
